## -*- mode: perl; -*-
(
# CMS - OpenExtensions with ASCII
    "zvm-common" => {
        inherit_from     => [ "BASE_unix" ],
        template         => 1,
        thread_scheme    => "pthreads",
        shared_target    => "self",
        shared_extension => "64.so.\$(SHLIB_VERSION_NUMBER)",
        cppflags         => "-DOPENSSL_THREADS -DB_ENDIAN -DNO_SYS_PARAM_H -D_THREAD_SAFE",
        bn_ops           => "SIXTY_FOUR_BIT RC4_CHAR DES_PTR DES_UNROLL MD2_CHAR RC4_INDEX BF_PTR",
    },
    "zvm-xlc" => {
        inherit_from     => [ "zvm-common" ],
        CC               => "xlc",
        CXX              => "xlC",
        CFLAGS           => picker(debug   => "-O0 -g",
                                   release => "-O3"),
        cflags           => "-q32 -qxplink -qascii -qenum=int -qlanglvl=extended:extc89:extc99 -qfloat=ieee -qlongname -qhaltonmsg=3296 -qasm -qnoansialias -qsuppress=3224",
        lflags           => "-q32 -L/usr/local/lib",
        cppflags         => add("-D_OPEN_SYS -D_XOPEN_SOURCE=600 -D_EXT -D_XOPEN_SOURCE_EXTENDED=1 -D_OPEN_MSGQ_EXT=1 -D_OPEN_SYS_SOCK_IPV6 -D_POSIX_SOURCE=1 -D_POSIX1_SOURCE=2 -D_POSIX_C_SOURCE=200112L -D_ISOC99_SOURCE=1 -D_ALL_SOURCE=1 -D_UNIX03_SOURCE=1 -D__VM__ -D_ENHANCED_ASCII_EXT=0xFFFFFFFF -I/usr/local/include"),
        shared_cflag     => "-qdll -qexportall",
        shared_ldflag    => "-Wl,dll",
        ex_libs          => add("-ltag /usr/local/lib/liboverride.x /usr/local/lib/libascii.x"),
    },
);
